# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='title',
            new_name='title_id',
        ),
        migrations.AddField(
            model_name='layout',
            name='icon',
            field=models.CharField(blank=True, default='fa fa-play', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
