# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20170522_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='text_block',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
    ]
